#!/usr/bin/env python3
"""PreToolUse guard for Project Kilowatt.

Blocks (exit code 2, reason sent back to Claude):
  1. Any read/search of simulator ground truth (data/ground_truth/**) - leakage guard.
  2. Code outside ml/ and the simulator that references ground_truth.
  3. Reading real env files (.env, .env.local, ...). .env.example is allowed.
  4. Reading private keys (*.key) and writing content that looks like a secret.

Fails open (exit 1 = non-blocking warning) if the hook itself errors, so a bug
here never bricks a session. Keep this file dependency-free (stdlib only).
"""
from __future__ import annotations

import json
import os
import re
import sys
from pathlib import PurePosixPath

PROJECT_DIR = os.environ.get("CLAUDE_PROJECT_DIR", os.getcwd()).replace("\\", "/").rstrip("/")

GROUND_TRUTH = "data/ground_truth"
# Paths allowed to *mention* ground_truth in code/docs (never to read the data via Claude).
GROUND_TRUTH_MENTION_OK = (
    "ml/",
    "services/simulator/",
    "docs/",
    ".claude/",
    "tests/ml/",
    "infra/compose/",
)
GROUND_TRUTH_MENTION_OK_FILES = ("CLAUDE.md", "README.md", ".gitignore", "Makefile")

ENV_FILE_RE = re.compile(r"^\.env(\..+)?$")
ENV_ALLOWED = {".env.example"}
BASH_READ_VERBS = r"(cat|less|more|head|tail|grep|rg|sed|awk|bat|strings|xxd|od|cp|mv|source|base64|printenv|type)"
BASH_ENV_RE = re.compile(BASH_READ_VERBS + r"\b[^|;&]*?(?<![\w.-])\.env(?!\.example)(\.[\w-]+)?\b")

SECRET_PATTERNS = [
    ("an AWS access key", re.compile(r"AKIA[0-9A-Z]{16}")),
    ("a private key block", re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH |DSA |ENCRYPTED )?PRIVATE KEY-----")),
    ("a GitHub token", re.compile(r"\bgh[pousr]_[A-Za-z0-9]{36,}")),
    ("an Anthropic API key", re.compile(r"\bsk-ant-[A-Za-z0-9_-]{20,}")),
    ("an OpenAI-style API key", re.compile(r"\bsk-(?:proj-)?[A-Za-z0-9]{32,}")),
    ("a Slack token", re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{10,}")),
    ("a Google API key", re.compile(r"\bAIza[0-9A-Za-z_-]{35}")),
]
GENERIC_SECRET_RE = re.compile(
    r"(?i)\b(password|passwd|secret|api[_-]?key|access[_-]?token|client[_-]?secret)\b\s*[:=]\s*['\"]([^'\"\s]{12,})['\"]"
)
PLACEHOLDER_HINTS = ("example", "changeme", "change-me", "dummy", "test", "fake", "placeholder",
                     "xxx", "<", "${", "dev-only", "local-only", "redacted")


def rel(path: str | None) -> str:
    if not path:
        return ""
    p = path.replace("\\", "/")
    if p.startswith(PROJECT_DIR + "/"):
        p = p[len(PROJECT_DIR) + 1:]
    return p.removeprefix("./")


def block(msg: str) -> None:
    print(f"[kilowatt guard] BLOCKED: {msg}", file=sys.stderr)
    sys.exit(2)


def check_path_read(path: str) -> None:
    if not path:
        return
    if GROUND_TRUTH in path:
        block(
            f"'{path}' is simulator ground truth. The pipeline and Claude must never read it "
            "(leakage guard, CLAUDE.md §6/§8). Evaluate models with `make ml-eval` instead."
        )
    name = PurePosixPath(path).name
    if ENV_FILE_RE.match(name) and name not in ENV_ALLOWED:
        block(f"'{path}' may contain real secrets. Use .env.example for variable names (CLAUDE.md §0.6).")
    if name.endswith(".key") or (name.endswith(".pem") and "key" in name.lower()):
        block(f"'{path}' looks like a private key. Keys are generated by infra/pki scripts and never read or committed.")


def check_content(path: str, content: str) -> None:
    if not content:
        return
    if path.startswith(".claude/hooks/"):
        return  # this file contains the patterns themselves
    for label, rx in SECRET_PATTERNS:
        if rx.search(content):
            block(f"content for '{path}' contains what looks like {label}. Put secrets in Vault/OpenBao and "
                  "reference them by env var; add only the variable name to .env.example.")
    if PurePosixPath(path).name != ".env.example":
        for m in GENERIC_SECRET_RE.finditer(content):
            value = m.group(2).lower()
            if not any(h in value for h in PLACEHOLDER_HINTS):
                block(f"'{path}' assigns a literal to '{m.group(1)}'. Load it from env/vault, or use an obvious "
                      "placeholder (e.g. 'changeme-dev-only') for local fixtures.")
    if "ground_truth" in content:
        ok = path.startswith(GROUND_TRUTH_MENTION_OK) or PurePosixPath(path).name in GROUND_TRUTH_MENTION_OK_FILES
        if not ok:
            block(f"'{path}' references ground_truth. Only ml/ evaluation code and the simulator (which writes it) "
                  "may touch it. Production services must never read it (CLAUDE.md §6).")


def main() -> None:
    data = json.load(sys.stdin)
    tool = data.get("tool_name", "")
    ti = data.get("tool_input", {}) or {}

    if tool == "Bash":
        cmd = ti.get("command", "")
        mentions_gt = GROUND_TRUTH in cmd or re.search(r"\bground_truth\b", cmd) is not None
        if mentions_gt and not cmd.strip().startswith("make ml-"):
            block("shell access to data/ground_truth is not allowed. Use `make ml-eval` for evaluation.")
        creating_from_example = re.fullmatch(r"\s*cp\s+(\./)?\.env\.example\s+(\./)?\.env[\w.-]*\s*", cmd)
        if BASH_ENV_RE.search(cmd) and not creating_from_example:
            block("reading .env files from the shell is not allowed. Use .env.example for variable names.")
        return

    if tool in ("Grep", "Glob"):
        target = rel(ti.get("path", "")) + " " + (ti.get("pattern", "") if tool == "Glob" else "") + " " + ti.get("glob", "")
        if GROUND_TRUTH in target:
            block("searching data/ground_truth is not allowed (leakage guard).")
        return

    path = rel(ti.get("file_path") or ti.get("notebook_path") or "")
    if tool == "Read":
        check_path_read(path)
        return

    if tool in ("Edit", "Write", "MultiEdit", "NotebookEdit"):
        if GROUND_TRUTH in path:
            block("only the simulator writes ground truth, at runtime. Don't edit it by hand.")
        name = PurePosixPath(path).name
        if ENV_FILE_RE.match(name) and name not in ENV_ALLOWED:
            block(f"don't write '{path}'. Only .env.example is committed; real values live in the vault or a local, untracked .env.")
        if tool == "Write":
            content = ti.get("content", "")
        elif tool == "Edit":
            content = ti.get("new_string", "")
        elif tool == "MultiEdit":
            content = "\n".join(e.get("new_string", "") for e in ti.get("edits", []))
        else:
            content = ti.get("new_source", "")
        check_content(path, content)


if __name__ == "__main__":
    try:
        main()
    except SystemExit:
        raise
    except Exception as exc:  # fail open, but visibly
        print(f"[kilowatt guard] hook error (not blocking): {exc}", file=sys.stderr)
        sys.exit(1)
    sys.exit(0)
